# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-03 11:52
from __future__ import unicode_literals

import contribmap.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribmap', '0003_auto_20160303_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrib',
            name='contrib_type',
            field=models.CharField(choices=[('connect', 'Me raccorder au réseau expérimental'), ('share', 'Partager une partie de ma connexion')], default='connect', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contrib',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contrib',
            name='name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contrib',
            name='orientations',
            field=contribmap.fields.CommaSeparatedCharField(blank=True, max_length=100, null=True),
        ),
    ]
