# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-03 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribmap', '0004_auto_20160303_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrib',
            name='access_type',
            field=models.CharField(blank=True, choices=[('vdsl', 'ADSL'), ('vdsl', 'VDSL'), ('fiber', 'Fibre optique'), ('cable', 'Coaxial (FTTLA)')], default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contrib',
            name='connect_internet',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contrib',
            name='connect_local',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contrib',
            name='floor',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contrib',
            name='floor_total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contrib',
            name='privacy_comment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contrib',
            name='privacy_coordinates',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contrib',
            name='privacy_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contrib',
            name='privacy_name',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contrib',
            name='privacy_place_details',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contrib',
            name='roof',
            field=models.BooleanField(default=False),
        ),
    ]
