# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-03 13:21
from __future__ import unicode_literals
import datetime
import pytz

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribmap', '0005_auto_20160303_1222'),
    ]

    operations = [
        migrations.RenameField('contrib', 'date', 'old_date'),
        migrations.AddField(
            model_name='contrib',
            name='date',
            field=models.DateTimeField(
                auto_now_add=True, default=datetime.datetime.now(pytz.utc)),
            preserve_default=False,
        ),
    ]
