# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-03 13:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contribmap', '0007_auto_20160303_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrib',
            name='old_date',
        ),
    ]
