# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-16 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribmap', '0010_auto_20160315_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrib',
            name='status',
            field=models.CharField(blank=True, choices=[('TOSTUDY', '\xe0 \xe9tudier'), ('TOCONNECT', '\xe0 connecter'), ('CONNECTED', 'connect\xe9'), ('WONTCONNECT', 'pas connectable')], default='A_ETUDIER', max_length=250, null=True),
        ),
    ]
